services:
  - type: web
    name: equipment-management-backend
    env: docker
    plan: free
    region: oregon
    rootDir: backend
    healthCheckPath: /
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: PORT
        value: 8080
