spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.huuodmmrcftfthyrmbqf.supabase.co:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:YOUR_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
